/* See license.txt for terms of usage */

"use strict";

const self = require("sdk/self");

// Add-on SDK
const { Cu, Ci } = require("chrome");
const { Class } = require("sdk/core/heritage");
const { Tool } = require("dev/toolbox");
const { defer } = require("sdk/core/promise");

// Firebug SDK
const { Content } = require("firebug.sdk/lib/core/content.js");
const { Str } = require("firebug.sdk/lib/core/string.js");
const { Locale } = require("firebug.sdk/lib/core/locale.js");
const { Dom } = require("firebug.sdk/lib/core/dom.js");

// Firebug
const { Trace, TraceError } = require("firebug.sdk/lib/core/trace.js").get(module.id);
const { BasePanel } = require("../chrome/base-panel.js");
const { GripProvider } = require("../dom/grip-provider.js");

// xxxHonza: part of the workaround for 1075490 (see the bottom of the file).
// Use the same weird panel ID that is generated by the SDK.
// There are places in the code (test, unregistering) that use the ID.
const panelId = "dev-panel-firebugsoftware-joehewitt-com-DOM2";

/**
 * This object represents a new {@Toolbox} panel
 */
const DomPanel = Class(
/** @lends DomPanel */
{
  extends: BasePanel,

  label: Locale.$STR("dom.panel.title"),
  tooltip: Locale.$STR("dom.panel.tip"),
  icon: "chrome://firebug/skin/tool-dom.png",
  url: "./dom/dom.html",
  searchable: true,

  initialize: function(options) {
    BasePanel.prototype.initialize.apply(this, arguments);

    this.onContentMessage = this.onContentMessage.bind(this);
    this.onGetPrototypeAndProperties = this.onGetPrototypeAndProperties.bind(this);
    this.onNavigate = this.onNavigate.bind(this);
  },

  dispose: function() {
  },

  onReady: function() {
    BasePanel.prototype.onReady.apply(this, arguments);

    Trace.sysout("DomPanel.onReady;", this.debuggee);

    let win = this.panelFrame.contentWindow;

    win.addEventListener("firebug/content/message",
      this.onContentMessage, true);
  },

  // Theme

  onApplyTheme: function(iframeWin, oldTheme) {
    Trace.sysout("domPanel.onApplyTheme;");
  },

  onUnapplyTheme: function(iframeWin, newTheme) {
    Trace.sysout("domPanel.onUnapplyTheme;");
  },

  // Search

  onSearch: function(text, reverse) {
    BasePanel.prototype.onSearch.apply(this, arguments);

    Trace.sysout("domPanel.onSearch; " + text);
  },

  findSearchResultContainer: function(node) {
    return Dom.getAncestorByClass(node, "memberRow");
  },

  // Toolbar

  getPanelToolbarButtons: function() {
    let buttons = [];

    buttons.push({
      label: "dom.refresh.label",
      tooltiptext: "dom.refresh.tip",
      command: this.onRefresh.bind(this)
    });

    return buttons;
  },

  // Commands

  onRefresh: function() {
    this.postContentMessage("refresh");
  },

  // Selection

  select: function(object) {
    Trace.sysout("domPanel.select; object:", object);
  },

  // Content Messages

  onContentReady: function() {
    Trace.sysout("DomPanel.onContentReady;", this.debuggee);

    let win = this.panelFrame.contentWindow;

    let contentTrace = {
      sysout: (msg, obj) => FBTrace.sysout(msg, obj)
    };

    Content.exportIntoContentScope(win, Str, "Str");
    Content.exportIntoContentScope(win, Locale, "Locale");
    Content.exportIntoContentScope(win, contentTrace, "Trace");
    Content.exportIntoContentScope(win, TraceError, "TraceError");

    // We need the thread object to get client object for grips
    // (using threadClient.pauseGrip).
    let target = this.toolbox.target;
    target.activeTab.attachThread({}, (response, threadClient) => {
      this.threadClient = threadClient;

      // Attach Console. It might involve RDP communication, so wait
      // asynchronously for the result
      this.attachConsole(threadClient).then(consoleClient => {
        Trace.sysout("DomPanel.update; consoleClient", consoleClient);

        // Evaluate an expression to get the top level actor.
        // The goal is to render that actor in the panel content.
        consoleClient.evaluateJS("window", (response) => {
          Trace.sysout("DomPanel.update; window grip received", response);

          this.postContentMessage("initialize", JSON.stringify(response.result));

          // Do not forget to resume the debugger.
          if (threadClient.paused) {
            threadClient.resume();
          }
        });
      });
    });
  },

  onGetPrototypeAndProperties: function(grip) {
    let provider = new GripProvider(this.toolbox.target);
    provider.getPrototypeAndProperties(grip).then(response => {
      this.postContentMessage("prototypeAndProperties",
        JSON.stringify(response));
    });
  },

  onNavigate: function(grip) {
  },

  // Tooltip Content Communication

  /**
   * Handle events coming from the tooltip iframe (content).
   */
  onContentMessage: function(event) {
    Trace.sysout("DomPanel.onContentMessage;", event);

    let { data } = event;
    switch (data.type) {
    case "ready":
      this.onContentReady(data.args);
      break;
    case "getPrototypeAndProperties":
      this.onGetPrototypeAndProperties(data.args);
      break;
    case "navigate":
      this.onNavigate(data.args);
      break;
    }
  },

  /**
   * Send message to the content scope (tooltip's iframe)
   */
  postContentMessage: function(type, args) {
    let win = this.panelFrame.contentWindow;

    var data = {
      type: type,
      args: args,
    };

    data = Content.cloneIntoContentScope(win, data);

    var event = new win.MessageEvent("firebug/chrome/message", {
      bubbles: true,
      cancelable: true,
      data: data,
    });

    win.dispatchEvent(event);

    Trace.sysout("DomPanel.postContentMessage; " + type, data);
  },

  // Helpers

  attachConsole: function(threadClient) {
    let deferred = defer();
    let debuggerClient = threadClient.client;
    let consoleActor = this.toolbox.target.form.consoleActor;

    debuggerClient.attachConsole(consoleActor, ["ConsoleAPI"],
      (response, webConsoleClient) => {

      Trace.sysout("DomPanel.attachConsole; ", arguments);

      if (response.error) {
        deferred.reject(response);
      } else {
        deferred.resolve(webConsoleClient);
      }
    });

    return deferred.promise;
  },
});

const myTool = new Tool({
  name: "MyTool2",
  panels: {
    DomPanel: DomPanel
  }
});

// Exports from this module
exports.DomPanel = DomPanel;
exports.domPanelId = panelId;
